#!/usr/bin/env ruby

require 'yaml'
require 'open-uri'
require 'openssl'
require 'open3'
require 'fileutils'
require 'find'
require 'optparse'

VERSION="v1.2"


def get_digest(checksum_method)
  case checksum_method
    when 'sha256'
      digest = OpenSSL::Digest::SHA256.new
    else
      raise "Did not recognise checksum_method"
  end
  digest
end

def digest_file(filename, checksum_method)
  digest = get_digest(checksum_method)
  File.open(filename, 'rb') do |io|
    while (buf = io.read(4096)) && buf.length > 0
      digest.update(buf)
    end
  end
  digest.hexdigest
end

def generate_tmp_filename
  "/tmp/filegrabber_#{Process.pid}_#{rand(500)}"
end

def import_rpm_key(config, file)
  stdout, status = Open3.capture2("#{config['rpm']} --import #{file}")
  raise "Import of RPM key #{file} failed!" if status != 0
end

def process_rpm_key(config, url, checksum_method, expected_checksum)
  tmpfile = generate_tmp_filename
  download_file(tmpfile, url)
  if validate_file(tmpfile, checksum_method, expected_checksum)
    puts "Key: Importing #{url} to the system rpm keyring"
    import_rpm_key(config, tmpfile)
  else
    raise "RPM Key '#{url}' does not match checksum."
  end
  File.delete(tmpfile)
end

def import_keys(config, keys)
  keys.each do |key|
    case key['type']
      when 'rpm'
        process_rpm_key(config, key['url'], key['checksum_method'], key['checksum'])
      else
        raise "Unknown key type '#{key['type']}'"
    end
  end
end

def generate_yum_config(url, name)
  <<-eos
[main]
reposdir=/dev/null

[#{name}]
name=#{name}
baseurl=#{url}
  eos
end

def vanilla_config
  <<-eof
---
config:
  basedir: '/mirror'
  rpm: '/usr/bin/rpm'
  reposync: '/usr/bin/reposync'
  yum_delete_on_signature_verify_fail: true
  yum_delete_missing_upstream: true
keys:
  -
    type: rpm
    url: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7
    checksum_method: sha256
    checksum: 8b48b04b336bd725b9e611c441c65456a4168083c4febc28e88828d8ec14827f
repos:
  -
    name: base
    path: repo/centos-7
    type: yum
    url: http://mirror.centos.org/centos-7/7/os/x86_64/
files:
  -
    name: putty.exe
    path: bin/putty
    url: https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe
    checksum_method: sha256
    checksum: 7afb56dd48565c3c9804f683c80ef47e5333f847f2d3211ec11ed13ad36061e1
  eof
end

def synchronise_yum_repo(config, yumconfig, targetdir)
  sync_command = "#{config['reposync']} -c #{yumconfig} -p #{targetdir}"
  sync_command += " -d" if config['yum_delete_missing_upstream']
  stdout, status = Open3.capture2(sync_command)
  raise "Sync failed" if status != 0
  # TODO: be more descriptive of the error
end

def validate_yum_repo(config, targetdir)
  Find.find(targetdir) do |f|
    if f =~ /.*\.rpm$/
      stdout, status = Open3.capture2("#{config['rpm']} -Kv #{f}")
      if status != 0
        puts "#{f} signature verification failed"
        if config['yum_delete_on_signature_verify_fail']
          puts "Deleting #{f}"
          File.delete(f) 
        end
      end
    end
  end
end

def import_repos(config, repos)
  repos.each do |repo|
    case repo['type']
      when 'yum'
        process_yum_repo(config, repo['name'], repo['url'], repo['path'])
      else
        raise "Unknown repo type '#{repo['type']}'"
    end
  end
end

def process_yum_repo(config, name, url, path)
  yumconfig = generate_tmp_filename
  File.write(yumconfig, generate_yum_config(url, name))
  targetdir = "#{config['basedir']}/#{path}"
  FileUtils.mkdir_p(targetdir)
  puts "Yum: Synchronising #{url} to #{targetdir}/#{name}"
  synchronise_yum_repo(config, yumconfig, targetdir)
  puts "Yum: Verifying signatures #{targetdir}/#{name}"
  validate_yum_repo(config, targetdir)
  File.delete(yumconfig)
end

def download_file(target, url)
  open(url, "rb") do |fin|
    fin.close
    FileUtils.mv(fin, target)
  end
end

def validate_file(filename, checksum_method, checksum)
  digest = digest_file(filename, checksum_method)
  checksum.eql?(digest)
end

def process_file(config, name, url, path, checksum_method, checksum)
  targetdir = "#{config['basedir']}/#{path}"
  finaldestination = "#{targetdir}/#{name}"
  if File.exists?(finaldestination)
      puts "File: #{name} already exists, revalidating checksum."
      if validate_file(finaldestination, checksum_method, checksum)
        puts "File: #{name} is good, skipping."
        return
      else
        puts "File: #{name} exists but the checksum is bad, redownloading."
      end
  end
  tmpfile = generate_tmp_filename
  # write file to disk in a temporary location
  puts "File: Downloading #{name}"
  download_file(tmpfile, url)
  puts "File: Verifying checksum on #{name}"
  if validate_file(tmpfile, checksum_method, checksum)
    FileUtils.mkdir_p(targetdir)
    puts "File: Checksum validation successful, moving to #{finaldestination}"
    FileUtils.mv(tmpfile, finaldestination)
  else
    puts "Checksum validation failed on #{name}. Not moving to the final destination"
    File.delete(tmpfile)
  end
end

def import_files(config, files)
  files.each do |file|
    process_file(config, file['name'], file['url'], file['path'], file['checksum_method'], file['checksum'])
  end
end

### Script begins here



options = {:keys => false, :repos => false, :files => false, :configfile => '/etc/securedownload'}

OptionParser.new do |opts|
  opts.banner = "Usage: securedownload [options]"

  opts.on('-k', '--key', 'Download keys') do |v|
    options[:keys] = true
  end

  opts.on('-f', '--file', 'Download files') do |v|
    options[:files] = true
  end

  opts.on('-r', '--repo', 'Download repos') do |v|
    options[:repos] = true
  end

  opts.on('-cFILE', '--config=FILE', 'Config file') do |v|
    options[:configfile] = v
  end

  opts.on('-b', '--bootstrap', 'Print a bootstrap configuration and exit') do |v|
    puts vanilla_config
    exit 1
  end

  opts.on('-v', '--version', 'Print version number and exit') do |v|
    puts VERSION
    exit
  end
end.parse!

if Process.euid != 0
  puts "This script has to be run as root"
  exit
end

puts "Using config file #{options[:configfile]}"
config = YAML.load(File.read(options[:configfile]))

if options[:keys]
  puts "Obtaining keys"
  import_keys(config['config'], config['keys'])
end

if options[:repos]
  puts "Obtaining repos"
  import_repos(config['config'], config['repos'])
end

if options[:files]
  puts "Obtaining files"
  import_files(config['config'], config['files'])
end